//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExperDBEntities : DbContext
    {
        public ExperDBEntities()
            : base("name=ExperDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Isci> Isci { get; set; }
        public virtual DbSet<IsciGecmis> IsciGecmis { get; set; }
        public virtual DbSet<İsciTalepleri> İsciTalepleri { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Makina> Makina { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
