//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Isci
    {
        public int Id { get; set; }
        public int GecmisId { get; set; }
        public decimal CiplakBrut { get; set; }
        public Nullable<decimal> Prim { get; set; }
        public Nullable<decimal> Yol { get; set; }
        public Nullable<decimal> Yemek { get; set; }
        public Nullable<decimal> GiydirilmisBrut { get; set; }
        public decimal Tavan { get; set; }
        public Nullable<System.DateTime> DavaTarihi { get; set; }
    
        public virtual IsciGecmis IsciGecmis { get; set; }
    }
}
