//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertService
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsciGecmis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IsciGecmis()
        {
            this.Isci = new HashSet<Isci>();
        }
    
        public int Id { get; set; }
        public System.DateTime IseGiris { get; set; }
        public System.DateTime IstenCikis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Isci> Isci { get; set; }
    }
}
