//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertService
{
    using System;
    using System.Collections.Generic;
    
    public partial class İsciTalepleri
    {
        public int Id { get; set; }
        public Nullable<decimal> KıdemTazminati { get; set; }
        public Nullable<decimal> IhbarTazminati { get; set; }
        public Nullable<decimal> FazlaMesai { get; set; }
        public Nullable<decimal> UGBT { get; set; }
        public Nullable<decimal> YillikIzin { get; set; }
        public Nullable<decimal> HaftaTatil { get; set; }
        public Nullable<decimal> Ucret { get; set; }
        public Nullable<decimal> AGI { get; set; }
        public Nullable<decimal> IseBaslatmamaTazm { get; set; }
        public Nullable<decimal> BostaGecenSure { get; set; }
    }
}
